stages:
 - test_windows
 - test_clang_tidy_windows
 - test_linux
 - test_clang_tidy_linux
 - test_windows_stress
 - test_linux_stress
 
## windows ---------------------------------------------------------------------
ci:windows:
 stage: test_windows
 needs: []
 tags:
  - windows
 script:
  - python -m venv venv
  - .\\venv\\Scripts\\python pybuilder\\pycmakebuilder.py 
    -d="$PWD" 
    --ctest-options="--output-on-failure 
                     --stop-on-failure 
                     -j12
                     --timeout 30"
    -i=""
    -e="pc_debug_gcc_clang_tidy|freertos_debug_gcc_clang_tidy"
 rules:
    # If merge request only no need start pipeline because pipeline was started when branch pushed in repo   
  - if: $CI_MERGE_REQUEST_EVENT_TYPE == "merge_train"
    when: always
    allow_failure: false
  - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    when: never
    allow_failure: false
    # When a push is made on a branch, we always want to start the pipeline
  - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
    when: always
  - if: $CI_PIPELINE_SOURCE == "schedule"
    when: always
    allow_failure: false
  - if: $CI_COMMIT_BRANCH == 'master'
    when: always
    allow_failure: false
  - when: never

ci:windows_clang_tidy:
 stage: test_clang_tidy_windows
 needs: []
 tags:
  - windows
 script:
  - python -m venv venv
  - .\\venv\\Scripts\\python pybuilder\\pycmakebuilder.py 
    -d="$PWD" 
    --ctest-options="--output-on-failure 
                     --stop-on-failure 
                     -j12
                     --timeout 30" 
    -i="pc_debug_gcc_clang_tidy|freertos_debug_gcc_clang_tidy"
 rules:
    # If merge request only no need start pipeline because pipeline was started when branch pushed in repo   
  - if: $CI_MERGE_REQUEST_EVENT_TYPE == "merge_train"
    when: always
    allow_failure: false
  - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    when: never
    allow_failure: false
    # When a push is made on a branch, we always want to start the pipeline
  - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
    when: always
  - if: $CI_PIPELINE_SOURCE == "schedule"
    when: always
    allow_failure: false
  - if: $CI_COMMIT_BRANCH == 'master'
    when: always
    allow_failure: false
  - when: never

ci:windows_stress_gcc:
 stage: test_windows_stress
 needs: []
 tags:
  - windows
 script:
  - python -m venv venv
  - .\\venv\\Scripts\\python pybuilder\\pycmakebuilder.py
    -d="$PWD" 
    --ctest-options="--output-on-failure 
                     --stop-on-failure 
                     -j12 
                     --repeat-until-fail 120
                     --timeout 30
                     -L [stress]" 
    -i="" 
    -e="pc_debug_clang_trace|
        freertos_debug_clang_trace|
        pc_debug_clang_docker|
        pc_debug_gcc_clang_tidy|
        freertos_debug_gcc_clang_tidy"
 rules:
  - if: $CI_MERGE_REQUEST_EVENT_TYPE == "merge_train"
    when: never
    allow_failure: false
  - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    when: always
    allow_failure: false
  - if: $CI_PIPELINE_SOURCE == "schedule"
    when: always
    allow_failure: false
  - if: $CI_COMMIT_BRANCH == 'master'
    when: always
    allow_failure: false


## Linux -----------------------------------------------------------------------
ci:linux:
 stage: test_linux
 needs: []
 tags:
  - linux
 script:
  - python3 -m venv venv
  - venv/bin/python3 pybuilder/pycmakebuilder.py 
    -d="${PWD}" 
    --ctest-options="--output-on-failure 
                     --stop-on-failure 
                     -j8
                     --timeout 30" 
    -i="" 
    -e="pc_debug_gcc_clang_tidy|freertos_debug_gcc_clang_tidy"
 rules:
    # If merge request only no need start pipeline because pipeline was started when branch pushed in repo   
  - if: $CI_MERGE_REQUEST_EVENT_TYPE == "merge_train"
    when: always
    allow_failure: false
  - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    when: never
    allow_failure: false
    # When a push is made on a branch, we always want to start the pipeline
  - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
    when: always
  - if: $CI_PIPELINE_SOURCE == "schedule"
    when: always
    allow_failure: false
  - if: $CI_COMMIT_BRANCH == 'master'
    when: always
    allow_failure: false
  - when: never

ci:linux_clang_tidy:
 stage: test_clang_tidy_linux
 needs: []
 tags:
  - linux
 script:
  - python3 -m venv venv
  - venv/bin/python3 pybuilder/pycmakebuilder.py 
    -d="${PWD}" 
    --ctest-options="--output-on-failure 
                     --stop-on-failure 
                     -j8
                     --timeout 30" 
    -i="pc_debug_gcc_clang_tidy|freertos_debug_gcc_clang_tidy"
 rules:
    # If merge request only no need start pipeline because pipeline was started when branch pushed in repo   
  - if: $CI_MERGE_REQUEST_EVENT_TYPE == "merge_train"
    when: always
    allow_failure: false
  - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    when: never
    allow_failure: false
    # When a push is made on a branch, we always want to start the pipeline
  - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
    when: always
  - if: $CI_PIPELINE_SOURCE == "schedule"
    when: always
    allow_failure: false
  - if: $CI_COMMIT_BRANCH == 'master'
    when: always
    allow_failure: false
  - when: never

ci:linux_stress_gcc:
 stage: test_linux_stress
 needs: []
 tags:
  - linux
 script:
  - python3 -m venv venv
  - venv/bin/python3 pybuilder/pycmakebuilder.py 
    -d="${PWD}" 
    --ctest-options="--output-on-failure 
                     --stop-on-failure 
                     -j8 
                     --repeat-until-fail 300
                     --timeout 30
                     -L [stress]" 
    -i="" 
    -e="pc_debug_clang_trace|
        freertos_debug_clang_trace|
        pc_debug_clang_docker|
        pc_debug_gcc_clang_tidy|
        freertos_debug_gcc_clang_tidy"
 rules:
  - if: $CI_MERGE_REQUEST_EVENT_TYPE == "merge_train"
    when: never
    allow_failure: false
  - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    when: always
    allow_failure: false
  - if: $CI_PIPELINE_SOURCE == "schedule"
    when: always
    allow_failure: false
  - if: $CI_COMMIT_BRANCH == 'master'
    when: always
    allow_failure: false